name: e_notepad
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #manejar el estado de la aplicación de manera reactiva y eficiente
  get: ^4.7.2
  #inicializar y conectar la app Flutter con Firebase
  firebase_core: ^3.13.0
  #base de datos en tiempo real de Firebase
  cloud_firestore: ^5.6.6
  #gestor de autenticación de Firebase
  firebase_auth: ^5.5.2
  #gestor de datos de forma local (persistente) en el dispositivo
  get_storage: ^2.1.1
  #seleccionar imágenes o videos desde la galería o la cámara del dispositivo
  image_picker: ^1.1.2
  #paquete para realizar peticiones HTTP
  http: ^1.3.0
  #paquete que permite identificar el tipo MIME (tipo de archivo)
  mime: ^2.0.0
  #parsear y manejar encabezados HTTP y tipos MIME
  http_parser: ^4.1.2
  #autenticación de usuarios mediante sus cuentas de Google
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  #seccion para definir recursos de la aplicacion
  assets:
    - assets/default_avatar.png
    - assets/google_logo.png
