// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJwVJTvklTERFk3_Q0vpQqKptIA_ljB9Y',
    appId: '1:1037867467592:web:ef3bf814074f7af0e3e97d',
    messagingSenderId: '1037867467592',
    projectId: 'e-notepad-b9648',
    authDomain: 'e-notepad-b9648.firebaseapp.com',
    storageBucket: 'e-notepad-b9648.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTP5piFW-XXYgXh93mhKwA5N2GCSmtWg',
    appId: '1:1037867467592:android:476766aee539c907e3e97d',
    messagingSenderId: '1037867467592',
    projectId: 'e-notepad-b9648',
    storageBucket: 'e-notepad-b9648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUq61uyBFK8GoyxfopnNotCjQAQrY0BJE',
    appId: '1:1037867467592:ios:c8a8636714b8cde0e3e97d',
    messagingSenderId: '1037867467592',
    projectId: 'e-notepad-b9648',
    storageBucket: 'e-notepad-b9648.firebasestorage.app',
    androidClientId: '1037867467592-umvq26bcigh7hria9itrf5c3tu8jonr9.apps.googleusercontent.com',
    iosClientId: '1037867467592-5h0ej2nsb483l8n8mutla5acor4ou0cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eNotepad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUq61uyBFK8GoyxfopnNotCjQAQrY0BJE',
    appId: '1:1037867467592:ios:c8a8636714b8cde0e3e97d',
    messagingSenderId: '1037867467592',
    projectId: 'e-notepad-b9648',
    storageBucket: 'e-notepad-b9648.firebasestorage.app',
    androidClientId: '1037867467592-umvq26bcigh7hria9itrf5c3tu8jonr9.apps.googleusercontent.com',
    iosClientId: '1037867467592-5h0ej2nsb483l8n8mutla5acor4ou0cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eNotepad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJwVJTvklTERFk3_Q0vpQqKptIA_ljB9Y',
    appId: '1:1037867467592:web:bd9c4d776f82d4e2e3e97d',
    messagingSenderId: '1037867467592',
    projectId: 'e-notepad-b9648',
    authDomain: 'e-notepad-b9648.firebaseapp.com',
    storageBucket: 'e-notepad-b9648.firebasestorage.app',
  );

}